[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yinyyW", email = "2936932419@qq.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn>=0.52.4",
]

[project.scripts]
backend = "app:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
